# Generated by Django 4.1.4 on 2023-02-04 11:26

import Core.ProjectMixins.Base.Save
import Core.fields.BigAutos.Id
import Core.fields.Booleans.IsActive
import Core.fields.Booleans.IsAdmin
import Core.fields.Booleans.IsCustomer
import Core.fields.Booleans.IsDelete
import Core.fields.Booleans.IsMarket
import Core.fields.Booleans.IsStaff
import Core.fields.Booleans.IsSuperUser
import Core.fields.Booleans.IsVerified
import Core.fields.Chars.PhoneNumber
import Core.fields.DateTimes.CreatedAt
import Core.fields.DateTimes.DeletedOn
import Core.fields.DateTimes.ModifiedAt
import Core.fields.OneToOnes.CustomerOneToOne
import Core.fields.OneToOnes.MarketOneToOne
import Core.fields.Slugs.Slug
import Users.managers
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customers', '0003_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Markets', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', Core.fields.BigAutos.Id.Id(db_index=True, help_text='Id of this User record', primary_key=True, serialize=False, unique=True, verbose_name='User`s Id')),
                ('phone_number', Core.fields.Chars.PhoneNumber.PhoneNumber(db_index=True, help_text='PhoneNumber of this User record', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='must be a phone number with 10 digits', regex='^(\\+98|\\+980|0098|00980|0|)(\\d{10})$')], verbose_name='User`s PhoneNumber')),
                ('is_customer', Core.fields.Booleans.IsCustomer.IsCustomer(db_index=True, default=True, help_text='Is this User record has costumer profile ?', verbose_name='Is Costumer')),
                ('is_market', Core.fields.Booleans.IsMarket.IsMarket(db_index=True, default=False, help_text='Is this User record has market profile ?', verbose_name='Is Market')),
                ('is_staff', Core.fields.Booleans.IsStaff.IsStaff(db_index=True, default=False, help_text='Is this User record has staff permissions ?', verbose_name='Is Staff')),
                ('is_active', Core.fields.Booleans.IsActive.IsActive(db_index=True, default=True, help_text='Is this User record available ?', verbose_name='User`s availability')),
                ('is_admin', Core.fields.Booleans.IsAdmin.IsAdmin(db_index=True, default=False, help_text='Is this User record has admin permissions ?', verbose_name='Is Admin')),
                ('is_superuser', Core.fields.Booleans.IsSuperUser.IsSuperUser(db_index=True, default=False, help_text='Is this User record has super user permissions ?', verbose_name='Is Super User')),
                ('is_verified', Core.fields.Booleans.IsVerified.IsVerified(db_index=True, default=False, help_text='Is this User record verified ?', verbose_name='Verified')),
                ('slug', Core.fields.Slugs.Slug.Slug(blank=True, help_text='Slugs of this User record', max_length=100, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Must be a valid slug)', regex='^[-a-zA-Z0-9_]+$')], verbose_name='User`s Slugs')),
                ('is_delete', Core.fields.Booleans.IsDelete.IsDelete(db_index=True, default=False, help_text='Is this User record has deleted ?', verbose_name='Is Delete')),
                ('deleted_on', Core.fields.DateTimes.DeletedOn.DeletedOn(blank=True, help_text='DeletedOn of this User record', null=True, verbose_name='User`s DeletedOn')),
                ('created_at', Core.fields.DateTimes.CreatedAt.CreatedAt(auto_now_add=True, help_text='CreatedAt of this User record', null=True, verbose_name='User`s CreatedAt')),
                ('modified_at', Core.fields.DateTimes.ModifiedAt.ModifiedAt(auto_now=True, help_text='ModifiedAt of this User record', null=True, verbose_name='User`s ModifiedAt')),
                ('customer', Core.fields.OneToOnes.CustomerOneToOne.CustomerOneToOne(blank=True, help_text='Customer of this User record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='Customers.customer', verbose_name='User`s Customer')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('market', Core.fields.OneToOnes.MarketOneToOne.MarketOneToOne(blank=True, help_text='Market of this User record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='Markets.market', verbose_name='User`s Market')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            bases=(models.Model, Core.ProjectMixins.Base.Save.SaveNormal),
            managers=[
                ('objects', Users.managers.CustomBaseUserManager()),
                ('subsets', Users.managers.CustomBaseUserManager()),
            ],
        ),
    ]
