# Generated by Django 4.1.4 on 2023-01-20 17:55

import Core.fields.ForeignKeys.CustomerForeignKey
import Core.fields.ForeignKeys.MarketForeignKey
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0006_cartitem_inventory_item'),
        ('Markets', '0002_inventory_date_close_inventory_date_open_and_more'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_costumer',
            new_name='is_customer',
        ),
        migrations.AddField(
            model_name='user',
            name='customer',
            field=Core.fields.ForeignKeys.CustomerForeignKey.CustomerForeignKey(blank=True, help_text='Customer of this User record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='Customers.customer', verbose_name='User`s Customer'),
        ),
        migrations.AddField(
            model_name='user',
            name='market',
            field=Core.fields.ForeignKeys.MarketForeignKey.MarketForeignKey(blank=True, help_text='Market of this User record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='Markets.market', verbose_name='User`s Market'),
        ),
    ]
