# Generated by Django 4.1.4 on 2023-01-21 08:53

import Core.fields.OneToOnes.CustomerOneToOne
import Core.fields.OneToOnes.MarketOneToOne
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Markets', '0003_alter_inventory_market_alter_market_user'),
        ('Customers', '0007_alter_cart_customer_alter_customer_user_and_more'),
        ('Users', '0002_rename_is_costumer_user_is_customer_user_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='customer',
            field=Core.fields.OneToOnes.CustomerOneToOne.CustomerOneToOne(help_text='Customer of this User record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='Customers.customer', verbose_name='User`s Customer'),
        ),
        migrations.AlterField(
            model_name='user',
            name='market',
            field=Core.fields.OneToOnes.MarketOneToOne.MarketOneToOne(help_text='Market of this User record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='Markets.market', verbose_name='User`s Market'),
        ),
    ]
