# Generated by Django 4.1.4 on 2023-02-04 11:26

import Core.fields.ForeignKeys.InventoryForeignKey
import Core.fields.ForeignKeys.InventoryItemForeignKey
import Core.fields.ForeignKeys.ProductForeignKey
import Core.fields.ForeignKeys.PropertyItemForeignKey
import Core.fields.ForeignKeys.ShipmentForeignKey
import Core.fields.ManyToManys.PropertyItemManyToMany
import Core.fields.OneToOnes.DiscountOneToOne
import Core.fields.OneToOnes.InventoryOneToOne
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Markets', '0001_initial'),
        ('Products', '0001_initial'),
        ('Shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermarket',
            name='shipment',
            field=Core.fields.ForeignKeys.ShipmentForeignKey.ShipmentForeignKey(blank=True, help_text='Order of this Market record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_market', to='Shops.shipment', verbose_name='Market`s Order'),
        ),
        migrations.AddField(
            model_name='market',
            name='inventory',
            field=Core.fields.OneToOnes.InventoryOneToOne.InventoryOneToOne(blank=True, help_text='Inventory of this Market record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market', to='Markets.inventory', verbose_name='Market`s Inventory'),
        ),
        migrations.AddField(
            model_name='inventoryitempropertyitem',
            name='inventoryitem_id',
            field=Core.fields.ForeignKeys.InventoryItemForeignKey.InventoryItemForeignKey(blank=True, help_text='Inventory of this Item record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_item_property_items', to='Markets.inventoryitem', verbose_name='Item`s Inventory'),
        ),
        migrations.AddField(
            model_name='inventoryitempropertyitem',
            name='propertyitem_id',
            field=Core.fields.ForeignKeys.PropertyItemForeignKey.PropertyItemForeignKey(blank=True, help_text='Inventory of this Item record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_item_property_items', to='Markets.propertyitem', verbose_name='Item`s Inventory'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='discount',
            field=Core.fields.OneToOnes.DiscountOneToOne.DiscountOneToOne(blank=True, help_text='Inventory of this Item record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_item', to='Shops.discount', verbose_name='Item`s Inventory'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='inventory',
            field=Core.fields.ForeignKeys.InventoryForeignKey.InventoryForeignKey(blank=True, help_text='Inventory of this Item record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='Markets.inventory', verbose_name='Item`s Inventory'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='product',
            field=Core.fields.ForeignKeys.ProductForeignKey.ProductForeignKey(blank=True, help_text='Inventory of this Item record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='Products.product', verbose_name='Item`s Inventory'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='property_item',
            field=Core.fields.ManyToManys.PropertyItemManyToMany.PropertyItemManyToMany(blank=True, db_index=True, help_text='Inventory of this Item record', related_name='inventory_items', through='Markets.InventoryItemPropertyItem', to='Markets.propertyitem', verbose_name='Item`s Inventory'),
        ),
    ]
