# Generated by Django 4.1.4 on 2023-01-21 08:53

import Core.fields.OneToOnes.MarketOneToOne
import Core.fields.OneToOnes.UserOneToOne
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Markets', '0002_inventory_date_close_inventory_date_open_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='market',
            field=Core.fields.OneToOnes.MarketOneToOne.MarketOneToOne(help_text='Market of this Inventory record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventorys', to='Markets.market', verbose_name='Inventory`s Market'),
        ),
        migrations.AlterField(
            model_name='market',
            name='user',
            field=Core.fields.OneToOnes.UserOneToOne.UserOneToOne(help_text='User of this Market record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='markets', to=settings.AUTH_USER_MODEL, verbose_name='Market`s User'),
        ),
    ]
