class REQUIREDFIELDS:
    ADDRESS = []
    COUPON = []
    DISCOUNT = []
    GALLERY = []
    IMAGE = []
    GALLERYIMAGE = []
    ORDER = []
    ORDERITEM = []
    PAYMENT = []
    WALLET = []
    SHIPMENT = []
    CONTACTUS = []
class SEARCHFIELDS:
    ADDRESS = []
    COUPON = []
    DISCOUNT = []
    GALLERY = []
    IMAGE = []
    GALLERYIMAGE = []
    ORDER = []
    ORDERITEM = []
    PAYMENT = []
    WALLET = []
    SHIPMENT = []
    CONTACTUS = []
