# Generated by Django 4.1.4 on 2025-12-18 03:08

import Core.ProjectMixins.Apps.Shops_Mixins.ModelRequiredProperties
import Core.fields.BoleanFields
import Core.fields.CharFields
import Core.fields.DateFields
import Core.fields.IdFields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', Core.fields.IdFields.CustomIdField(db_index=True, help_text='Id of this Model record', primary_key=True, serialize=False, verbose_name='Model`s Id')),
                ('is_delete', Core.fields.BoleanFields.CustomIsDeletedField(db_index=True, default=False, help_text='Is this Model record deleted ?', verbose_name='Is Deleted')),
                ('created_at', Core.fields.DateFields.CustomCreatedAtField(auto_now_add=True, help_text='When this Model record was created', null=True, verbose_name='Created At')),
                ('modified_at', Core.fields.DateFields.CustomModifiedAtField(auto_now=True, help_text='When this Model record was modified', null=True, verbose_name='Modified At')),
                ('name', Core.fields.CharFields.CustomNameField(db_index=True, help_text='Name of this Address record', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='must be a valid name with 3 to 30 characters', regex='^.{3,30}$')], verbose_name='Address`s Name')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresss',
            },
            bases=(Core.ProjectMixins.Apps.Shops_Mixins.ModelRequiredProperties.AddressMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', Core.fields.IdFields.CustomIdField(db_index=True, help_text='Id of this Model record', primary_key=True, serialize=False, verbose_name='Model`s Id')),
                ('is_delete', Core.fields.BoleanFields.CustomIsDeletedField(db_index=True, default=False, help_text='Is this Model record deleted ?', verbose_name='Is Deleted')),
                ('created_at', Core.fields.DateFields.CustomCreatedAtField(auto_now_add=True, help_text='When this Model record was created', null=True, verbose_name='Created At')),
                ('modified_at', Core.fields.DateFields.CustomModifiedAtField(auto_now=True, help_text='When this Model record was modified', null=True, verbose_name='Modified At')),
                ('name', Core.fields.CharFields.CustomNameField(db_index=True, help_text='Contact of this Us record', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='must be a valid name with 3 to 30 characters', regex='^.{3,30}$')], verbose_name='Us`s Contact')),
            ],
            options={
                'verbose_name': 'ContactUs',
                'verbose_name_plural': 'ContactUss',
            },
            bases=(Core.ProjectMixins.Apps.Shops_Mixins.ModelRequiredProperties.ContactUsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', Core.fields.IdFields.CustomIdField(db_index=True, help_text='Id of this Model record', primary_key=True, serialize=False, verbose_name='Model`s Id')),
                ('is_delete', Core.fields.BoleanFields.CustomIsDeletedField(db_index=True, default=False, help_text='Is this Model record deleted ?', verbose_name='Is Deleted')),
                ('created_at', Core.fields.DateFields.CustomCreatedAtField(auto_now_add=True, help_text='When this Model record was created', null=True, verbose_name='Created At')),
                ('modified_at', Core.fields.DateFields.CustomModifiedAtField(auto_now=True, help_text='When this Model record was modified', null=True, verbose_name='Modified At')),
                ('name', Core.fields.CharFields.CustomNameField(db_index=True, help_text='Name of this Coupon record', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='must be a valid name with 3 to 30 characters', regex='^.{3,30}$')], verbose_name='Coupon`s Name')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
            },
            bases=(Core.ProjectMixins.Apps.Shops_Mixins.ModelRequiredProperties.CouponMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', Core.fields.IdFields.CustomIdField(db_index=True, help_text='Id of this Model record', primary_key=True, serialize=False, verbose_name='Model`s Id')),
                ('is_delete', Core.fields.BoleanFields.CustomIsDeletedField(db_index=True, default=False, help_text='Is this Model record deleted ?', verbose_name='Is Deleted')),
                ('created_at', Core.fields.DateFields.CustomCreatedAtField(auto_now_add=True, help_text='When this Model record was created', null=True, verbose_name='Created At')),
                ('modified_at', Core.fields.DateFields.CustomModifiedAtField(auto_now=True, help_text='When this Model record was modified', null=True, verbose_name='Modified At')),
                ('name', Core.fields.CharFields.CustomNameField(db_index=True, help_text='Name of this Discount record', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='must be a valid name with 3 to 30 characters', regex='^.{3,30}$')], verbose_name='Discount`s Name')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
            },
            bases=(Core.ProjectMixins.Apps.Shops_Mixins.ModelRequiredProperties.DiscountMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', Core.fields.IdFields.CustomIdField(db_index=True, help_text='Id of this Model record', primary_key=True, serialize=False, verbose_name='Model`s Id')),
                ('is_delete', Core.fields.BoleanFields.CustomIsDeletedField(db_index=True, default=False, help_text='Is this Model record deleted ?', verbose_name='Is Deleted')),
                ('created_at', Core.fields.DateFields.CustomCreatedAtField(auto_now_add=True, help_text='When this Model record was created', null=True, verbose_name='Created At')),
                ('modified_at', Core.fields.DateFields.CustomModifiedAtField(auto_now=True, help_text='When this Model record was modified', null=True, verbose_name='Modified At')),
                ('name', Core.fields.CharFields.CustomNameField(db_index=True, help_text='Name of this Gallery record', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='must be a valid name with 3 to 30 characters', regex='^.{3,30}$')], verbose_name='Gallery`s Name')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Gallerys',
            },
            bases=(Core.ProjectMixins.Apps.Shops_Mixins.ModelRequiredProperties.GalleryMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', Core.fields.IdFields.CustomIdField(db_index=True, help_text='Id of this Model record', primary_key=True, serialize=False, verbose_name='Model`s Id')),
                ('is_delete', Core.fields.BoleanFields.CustomIsDeletedField(db_index=True, default=False, help_text='Is this Model record deleted ?', verbose_name='Is Deleted')),
                ('created_at', Core.fields.DateFields.CustomCreatedAtField(auto_now_add=True, help_text='When this Model record was created', null=True, verbose_name='Created At')),
                ('modified_at', Core.fields.DateFields.CustomModifiedAtField(auto_now=True, help_text='When this Model record was modified', null=True, verbose_name='Modified At')),
                ('name', Core.fields.CharFields.CustomNameField(db_index=True, help_text='Name of this Image record', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='must be a valid name with 3 to 30 characters', regex='^.{3,30}$')], verbose_name='Image`s Name')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
            bases=(Core.ProjectMixins.Apps.Shops_Mixins.ModelRequiredProperties.ImageMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', Core.fields.IdFields.CustomIdField(db_index=True, help_text='Id of this Model record', primary_key=True, serialize=False, verbose_name='Model`s Id')),
                ('is_delete', Core.fields.BoleanFields.CustomIsDeletedField(db_index=True, default=False, help_text='Is this Model record deleted ?', verbose_name='Is Deleted')),
                ('created_at', Core.fields.DateFields.CustomCreatedAtField(auto_now_add=True, help_text='When this Model record was created', null=True, verbose_name='Created At')),
                ('modified_at', Core.fields.DateFields.CustomModifiedAtField(auto_now=True, help_text='When this Model record was modified', null=True, verbose_name='Modified At')),
                ('name', Core.fields.CharFields.CustomNameField(db_index=True, help_text='Name of this Order record', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='must be a valid name with 3 to 30 characters', regex='^.{3,30}$')], verbose_name='Order`s Name')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
            bases=(Core.ProjectMixins.Apps.Shops_Mixins.ModelRequiredProperties.OrderMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', Core.fields.IdFields.CustomIdField(db_index=True, help_text='Id of this Model record', primary_key=True, serialize=False, verbose_name='Model`s Id')),
                ('is_delete', Core.fields.BoleanFields.CustomIsDeletedField(db_index=True, default=False, help_text='Is this Model record deleted ?', verbose_name='Is Deleted')),
                ('created_at', Core.fields.DateFields.CustomCreatedAtField(auto_now_add=True, help_text='When this Model record was created', null=True, verbose_name='Created At')),
                ('modified_at', Core.fields.DateFields.CustomModifiedAtField(auto_now=True, help_text='When this Model record was modified', null=True, verbose_name='Modified At')),
                ('name', Core.fields.CharFields.CustomNameField(db_index=True, help_text='Order of this Item record', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='must be a valid name with 3 to 30 characters', regex='^.{3,30}$')], verbose_name='Item`s Order')),
            ],
            options={
                'verbose_name': 'OrderItem',
                'verbose_name_plural': 'OrderItems',
            },
            bases=(Core.ProjectMixins.Apps.Shops_Mixins.ModelRequiredProperties.OrderItemMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', Core.fields.IdFields.CustomIdField(db_index=True, help_text='Id of this Model record', primary_key=True, serialize=False, verbose_name='Model`s Id')),
                ('is_delete', Core.fields.BoleanFields.CustomIsDeletedField(db_index=True, default=False, help_text='Is this Model record deleted ?', verbose_name='Is Deleted')),
                ('created_at', Core.fields.DateFields.CustomCreatedAtField(auto_now_add=True, help_text='When this Model record was created', null=True, verbose_name='Created At')),
                ('modified_at', Core.fields.DateFields.CustomModifiedAtField(auto_now=True, help_text='When this Model record was modified', null=True, verbose_name='Modified At')),
                ('name', Core.fields.CharFields.CustomNameField(db_index=True, help_text='Name of this Payment record', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='must be a valid name with 3 to 30 characters', regex='^.{3,30}$')], verbose_name='Payment`s Name')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
            bases=(Core.ProjectMixins.Apps.Shops_Mixins.ModelRequiredProperties.PaymentMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', Core.fields.IdFields.CustomIdField(db_index=True, help_text='Id of this Model record', primary_key=True, serialize=False, verbose_name='Model`s Id')),
                ('is_delete', Core.fields.BoleanFields.CustomIsDeletedField(db_index=True, default=False, help_text='Is this Model record deleted ?', verbose_name='Is Deleted')),
                ('created_at', Core.fields.DateFields.CustomCreatedAtField(auto_now_add=True, help_text='When this Model record was created', null=True, verbose_name='Created At')),
                ('modified_at', Core.fields.DateFields.CustomModifiedAtField(auto_now=True, help_text='When this Model record was modified', null=True, verbose_name='Modified At')),
                ('name', Core.fields.CharFields.CustomNameField(db_index=True, help_text='Name of this Shipment record', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='must be a valid name with 3 to 30 characters', regex='^.{3,30}$')], verbose_name='Shipment`s Name')),
            ],
            options={
                'verbose_name': 'Shipment',
                'verbose_name_plural': 'Shipments',
            },
            bases=(Core.ProjectMixins.Apps.Shops_Mixins.ModelRequiredProperties.ShipmentMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', Core.fields.IdFields.CustomIdField(db_index=True, help_text='Id of this Model record', primary_key=True, serialize=False, verbose_name='Model`s Id')),
                ('is_delete', Core.fields.BoleanFields.CustomIsDeletedField(db_index=True, default=False, help_text='Is this Model record deleted ?', verbose_name='Is Deleted')),
                ('created_at', Core.fields.DateFields.CustomCreatedAtField(auto_now_add=True, help_text='When this Model record was created', null=True, verbose_name='Created At')),
                ('modified_at', Core.fields.DateFields.CustomModifiedAtField(auto_now=True, help_text='When this Model record was modified', null=True, verbose_name='Modified At')),
                ('name', Core.fields.CharFields.CustomNameField(db_index=True, help_text='Shipment of this Item record', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='must be a valid name with 3 to 30 characters', regex='^.{3,30}$')], verbose_name='Item`s Shipment')),
            ],
            options={
                'verbose_name': 'ShipmentItem',
                'verbose_name_plural': 'ShipmentItems',
            },
            bases=(Core.ProjectMixins.Apps.Shops_Mixins.ModelRequiredProperties.ShipmentItemMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', Core.fields.IdFields.CustomIdField(db_index=True, help_text='Id of this Model record', primary_key=True, serialize=False, verbose_name='Model`s Id')),
                ('is_delete', Core.fields.BoleanFields.CustomIsDeletedField(db_index=True, default=False, help_text='Is this Model record deleted ?', verbose_name='Is Deleted')),
                ('created_at', Core.fields.DateFields.CustomCreatedAtField(auto_now_add=True, help_text='When this Model record was created', null=True, verbose_name='Created At')),
                ('modified_at', Core.fields.DateFields.CustomModifiedAtField(auto_now=True, help_text='When this Model record was modified', null=True, verbose_name='Modified At')),
                ('name', Core.fields.CharFields.CustomNameField(db_index=True, help_text='Name of this Wallet record', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='must be a valid name with 3 to 30 characters', regex='^.{3,30}$')], verbose_name='Wallet`s Name')),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
            bases=(Core.ProjectMixins.Apps.Shops_Mixins.ModelRequiredProperties.WalletMixin, models.Model),
        ),
    ]
