# Generated by Django 4.1.4 on 2023-01-20 17:55

import Core.fields.ForeignKeys.InventoryItemForeignKey
import Core.fields.ForeignKeys.OrderMarketForeignKey
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Markets', '0002_inventory_date_close_inventory_date_open_and_more'),
        ('Shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='inventory_item',
            field=Core.fields.ForeignKeys.InventoryItemForeignKey.InventoryItemForeignKey(blank=True, help_text='InventoryItem of this Discount record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discounts', to='Markets.inventoryitem', verbose_name='Discount`s InventoryItem'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_market',
            field=Core.fields.ForeignKeys.OrderMarketForeignKey.OrderMarketForeignKey(blank=True, help_text='OrderMarket of this Order record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='Markets.ordermarket', verbose_name='Order`s OrderMarket'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='inventory_item',
            field=Core.fields.ForeignKeys.InventoryItemForeignKey.InventoryItemForeignKey(blank=True, help_text='Order of this Item record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderitems', to='Markets.inventoryitem', verbose_name='Item`s Order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_market',
            field=Core.fields.ForeignKeys.OrderMarketForeignKey.OrderMarketForeignKey(blank=True, help_text='Order of this Item record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderitems', to='Markets.ordermarket', verbose_name='Item`s Order'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='order_market',
            field=Core.fields.ForeignKeys.OrderMarketForeignKey.OrderMarketForeignKey(blank=True, help_text='OrderMarket of this Shipment record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='Markets.ordermarket', verbose_name='Shipment`s OrderMarket'),
        ),
    ]
