# Generated by Django 4.1.4 on 2025-12-18 05:29

import Core.fields.DecimalFields
import Core.fields.ForeignKeys
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Products', '0002_initial'),
        ('Shops', '0002_alter_address_options_alter_contactus_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=Core.fields.ForeignKeys.CustomAddressFieldForeignKey(blank=True, help_text='Address of this Order record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='Shops.address', verbose_name='Order`s Address'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=Core.fields.DecimalFields.CustomPriceDollarField(db_index=True, decimal_places=2, default=0.0, help_text='Dollar Price of this Order record', max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Price must be at least 0'), django.core.validators.MaxValueValidator(1000000000, message='Price must be at most 1000000000')], verbose_name='Order`s Dollar Price'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=Core.fields.ForeignKeys.CustomUserFieldForeignKey(help_text='User of this Order record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Order`s User'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=Core.fields.ForeignKeys.CustomOrderFieldForeignKey(blank=True, help_text='Order of this Item record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderitems', to='Shops.order', verbose_name='Item`s Order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=Core.fields.DecimalFields.CustomPriceDollarField(db_index=True, decimal_places=2, default=0.0, help_text='Order of this Item record', max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Price must be at least 0'), django.core.validators.MaxValueValidator(1000000000, message='Price must be at most 1000000000')], verbose_name='Item`s Order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=Core.fields.ForeignKeys.CustomProductFieldForeignKey(blank=True, help_text='Order of this Item record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderitems', to='Products.product', verbose_name='Item`s Order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
