# Generated by Django 4.1.4 on 2025-12-18 05:31

import Core.fields.SlugFields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shops', '0003_order_address_order_total_price_order_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='slug',
            field=Core.fields.SlugFields.CustomSlugField(blank=True, help_text='Slug of this Address record', max_length=100, null=True, unique=True, verbose_name='Address`s Slug'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='slug',
            field=Core.fields.SlugFields.CustomSlugField(blank=True, help_text='Contact of this Us record', max_length=100, null=True, unique=True, verbose_name='Us`s Contact'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='slug',
            field=Core.fields.SlugFields.CustomSlugField(blank=True, help_text='Slug of this Coupon record', max_length=100, null=True, unique=True, verbose_name='Coupon`s Slug'),
        ),
        migrations.AddField(
            model_name='discount',
            name='slug',
            field=Core.fields.SlugFields.CustomSlugField(blank=True, help_text='Slug of this Discount record', max_length=100, null=True, unique=True, verbose_name='Discount`s Slug'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='slug',
            field=Core.fields.SlugFields.CustomSlugField(blank=True, help_text='Slug of this Gallery record', max_length=100, null=True, unique=True, verbose_name='Gallery`s Slug'),
        ),
        migrations.AddField(
            model_name='image',
            name='slug',
            field=Core.fields.SlugFields.CustomSlugField(blank=True, help_text='Slug of this Image record', max_length=100, null=True, unique=True, verbose_name='Image`s Slug'),
        ),
        migrations.AddField(
            model_name='order',
            name='slug',
            field=Core.fields.SlugFields.CustomSlugField(blank=True, help_text='Slug of this Order record', max_length=100, null=True, unique=True, verbose_name='Order`s Slug'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='slug',
            field=Core.fields.SlugFields.CustomSlugField(blank=True, help_text='Order of this Item record', max_length=100, null=True, unique=True, verbose_name='Item`s Order'),
        ),
        migrations.AddField(
            model_name='payment',
            name='slug',
            field=Core.fields.SlugFields.CustomSlugField(blank=True, help_text='Slug of this Payment record', max_length=100, null=True, unique=True, verbose_name='Payment`s Slug'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='slug',
            field=Core.fields.SlugFields.CustomSlugField(blank=True, help_text='Slug of this Shipment record', max_length=100, null=True, unique=True, verbose_name='Shipment`s Slug'),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='slug',
            field=Core.fields.SlugFields.CustomSlugField(blank=True, help_text='Shipment of this Item record', max_length=100, null=True, unique=True, verbose_name='Item`s Shipment'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='slug',
            field=Core.fields.SlugFields.CustomSlugField(blank=True, help_text='Slug of this Wallet record', max_length=100, null=True, unique=True, verbose_name='Wallet`s Slug'),
        ),
    ]
