# Generated by Django 4.1.4 on 2023-02-04 11:26

import Core.fields.ForeignKeys.CustomerForeignKey
import Core.fields.ForeignKeys.ProductForeignKey
import Core.fields.ForeignKeys.WishListForeignKey
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0001_initial'),
        ('Customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='product',
            field=Core.fields.ForeignKeys.ProductForeignKey.ProductForeignKey(blank=True, help_text='Wish of this List record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='Products.product', verbose_name='List`s Wish'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='wish_list',
            field=Core.fields.ForeignKeys.WishListForeignKey.WishListForeignKey(blank=True, help_text='Wish of this List record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='Customers.wishlist', verbose_name='List`s Wish'),
        ),
        migrations.AddField(
            model_name='ordercustomer',
            name='coupon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Customers.customercoupon'),
        ),
        migrations.AddField(
            model_name='ordercustomer',
            name='customer',
            field=Core.fields.ForeignKeys.CustomerForeignKey.CustomerForeignKey(blank=True, help_text='Order of this Customer record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='Customers.customer', verbose_name='Customer`s Order'),
        ),
    ]
