# Generated by Django 4.1.4 on 2023-01-20 17:06

import Core.fields.ForeignKeys.CouponCustomerCouponForeignKey
import Core.fields.ForeignKeys.CustomerForeignKey
import Core.fields.ForeignKeys.ProductForeignKey
import Core.fields.ForeignKeys.WishListForeignKey
import Core.fields.ForeignKeys.WishListItemForeignKey
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0001_initial'),
        ('Customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='product',
            field=Core.fields.ForeignKeys.ProductForeignKey.ProductForeignKey(blank=True, help_text='Wish of this List record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wishlistitems', to='Products.product', verbose_name='List`s Wish'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='wish_list',
            field=Core.fields.ForeignKeys.WishListForeignKey.WishListForeignKey(blank=True, help_text='Wish of this List record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wishlistitems', to='Customers.wishlist', verbose_name='List`s Wish'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='customer',
            field=Core.fields.ForeignKeys.CustomerForeignKey.CustomerForeignKey(blank=True, help_text='Customer of this Wishlist record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wishlists', to='Customers.customer', verbose_name='Wishlist`s Customer'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='wish_list_item',
            field=Core.fields.ForeignKeys.WishListItemForeignKey.WishListItemForeignKey(blank=True, help_text='WishListItem of this Wishlist record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wishlists', to='Customers.wishlistitem', verbose_name='Wishlist`s WishListItem'),
        ),
        migrations.AddField(
            model_name='ordercustomer',
            name='CouponCustomerCoupon',
            field=Core.fields.ForeignKeys.CouponCustomerCouponForeignKey.CouponCustomerCouponForeignKey(blank=True, help_text='Order of this Customer record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordercustomers', to='Customers.customercoupon', verbose_name='Customer`s Order'),
        ),
        migrations.AddField(
            model_name='ordercustomer',
            name='customer',
            field=Core.fields.ForeignKeys.CustomerForeignKey.CustomerForeignKey(blank=True, help_text='Order of this Customer record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordercustomers', to='Customers.customer', verbose_name='Customer`s Order'),
        ),
    ]
