# Generated by Django 4.1.4 on 2023-02-04 11:26

import Core.fields.ForeignKeys.CartForeignKey
import Core.fields.ForeignKeys.CouponForeignKey
import Core.fields.ForeignKeys.CustomerForeignKey
import Core.fields.ForeignKeys.FavoriteForeignKey
import Core.fields.ForeignKeys.InventoryItemForeignKey
import Core.fields.ForeignKeys.ProductForeignKey
import Core.fields.ForeignKeys.ShipmentForeignKey
import Core.fields.OneToOnes.CartOneToOne
import Core.fields.OneToOnes.FavoriteOneToOne
import Core.fields.OneToOnes.WishListOneToOne
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Markets', '0001_initial'),
        ('Products', '0001_initial'),
        ('Shops', '0001_initial'),
        ('Customers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercustomer',
            name='shipment',
            field=Core.fields.ForeignKeys.ShipmentForeignKey.ShipmentForeignKey(blank=True, help_text='Order of this Customer record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_customer', to='Shops.shipment', verbose_name='Customer`s Order'),
        ),
        migrations.AddField(
            model_name='favoriteitem',
            name='favorite',
            field=Core.fields.ForeignKeys.FavoriteForeignKey.FavoriteForeignKey(blank=True, help_text='Favorite of this Item record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_items', to='Customers.favorite', verbose_name='Item`s Favorite'),
        ),
        migrations.AddField(
            model_name='favoriteitem',
            name='product',
            field=Core.fields.ForeignKeys.ProductForeignKey.ProductForeignKey(blank=True, help_text='Favorite of this Item record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_items', to='Products.product', verbose_name='Item`s Favorite'),
        ),
        migrations.AddField(
            model_name='customercoupon',
            name='coupon_id',
            field=Core.fields.ForeignKeys.CouponForeignKey.CouponForeignKey(blank=True, help_text='Customer of this Coupon record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='Customers.coupon', verbose_name='Coupon`s Customer'),
        ),
        migrations.AddField(
            model_name='customercoupon',
            name='customer_id',
            field=Core.fields.ForeignKeys.CustomerForeignKey.CustomerForeignKey(blank=True, help_text='Customer of this Coupon record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='Customers.customer', verbose_name='Coupon`s Customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='cart',
            field=Core.fields.OneToOnes.CartOneToOne.CartOneToOne(blank=True, help_text='Cart of this Customer record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='Customers.cart', verbose_name='Customer`s Cart'),
        ),
        migrations.AddField(
            model_name='customer',
            name='favorite',
            field=Core.fields.OneToOnes.FavoriteOneToOne.FavoriteOneToOne(blank=True, help_text='Favorite of this Customer record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='Customers.favorite', verbose_name='Customer`s Favorite'),
        ),
        migrations.AddField(
            model_name='customer',
            name='wishlist',
            field=Core.fields.OneToOnes.WishListOneToOne.WishListOneToOne(blank=True, help_text='WishList of this Customer record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='Customers.wishlist', verbose_name='Customer`s WishList'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=Core.fields.ForeignKeys.CartForeignKey.CartForeignKey(blank=True, help_text='Cart of this Item record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='Customers.cart', verbose_name='Item`s Cart'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='inventory_item',
            field=Core.fields.ForeignKeys.InventoryItemForeignKey.InventoryItemForeignKey(blank=True, help_text='Cart of this Item record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='Markets.inventoryitem', verbose_name='Item`s Cart'),
        ),
    ]
