# Generated by Django 4.1.4 on 2023-01-20 17:06

import Core.fields.ForeignKeys.CartForeignKey
import Core.fields.ForeignKeys.CommentForeignKey
import Core.fields.ForeignKeys.CouponForeignKey
import Core.fields.ForeignKeys.CustomerForeignKey
import Core.fields.ForeignKeys.FavoriteForeignKey
import Core.fields.ForeignKeys.FavoriteItemForeignKey
import Core.fields.ForeignKeys.OrderCustomerForeignKey
import Core.fields.ForeignKeys.OrderForeignKey
import Core.fields.ForeignKeys.OrderItemForeignKey
import Core.fields.ForeignKeys.ProductForeignKey
import Core.fields.ForeignKeys.ShipmentForeignKey
import Core.fields.ManyToManys.CouponManyToMany
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0001_initial'),
        ('Shops', '0001_initial'),
        ('Customers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercustomer',
            name='order',
            field=Core.fields.ForeignKeys.OrderForeignKey.OrderForeignKey(blank=True, help_text='Order of this Customer record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordercustomers', to='Shops.order', verbose_name='Customer`s Order'),
        ),
        migrations.AddField(
            model_name='ordercustomer',
            name='order_item',
            field=Core.fields.ForeignKeys.OrderItemForeignKey.OrderItemForeignKey(blank=True, help_text='Order of this Customer record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordercustomers', to='Shops.orderitem', verbose_name='Customer`s Order'),
        ),
        migrations.AddField(
            model_name='ordercustomer',
            name='shipment',
            field=Core.fields.ForeignKeys.ShipmentForeignKey.ShipmentForeignKey(blank=True, help_text='Order of this Customer record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordercustomers', to='Shops.shipment', verbose_name='Customer`s Order'),
        ),
        migrations.AddField(
            model_name='favoriteitem',
            name='favorite',
            field=Core.fields.ForeignKeys.FavoriteForeignKey.FavoriteForeignKey(blank=True, help_text='Favorite of this Item record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favoriteitems', to='Customers.favorite', verbose_name='Item`s Favorite'),
        ),
        migrations.AddField(
            model_name='favoriteitem',
            name='product',
            field=Core.fields.ForeignKeys.ProductForeignKey.ProductForeignKey(blank=True, help_text='Favorite of this Item record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favoriteitems', to='Products.product', verbose_name='Item`s Favorite'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='customer',
            field=Core.fields.ForeignKeys.CustomerForeignKey.CustomerForeignKey(blank=True, help_text='Customer of this Favorite record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorites', to='Customers.customer', verbose_name='Favorite`s Customer'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='favorite_item',
            field=Core.fields.ForeignKeys.FavoriteItemForeignKey.FavoriteItemForeignKey(blank=True, help_text='FavoriteItem of this Favorite record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorites', to='Customers.favoriteitem', verbose_name='Favorite`s FavoriteItem'),
        ),
        migrations.AddField(
            model_name='customercoupon',
            name='coupon_id',
            field=Core.fields.ForeignKeys.CouponForeignKey.CouponForeignKey(blank=True, help_text='Customer of this Coupon record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customercoupons', to='Customers.coupon', verbose_name='Coupon`s Customer'),
        ),
        migrations.AddField(
            model_name='customercoupon',
            name='customer_id',
            field=Core.fields.ForeignKeys.CustomerForeignKey.CustomerForeignKey(blank=True, help_text='Customer of this Coupon record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customercoupons', to='Customers.customer', verbose_name='Coupon`s Customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='cart',
            field=Core.fields.ForeignKeys.CartForeignKey.CartForeignKey(blank=True, help_text='Cart of this Customer record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='Customers.cart', verbose_name='Customer`s Cart'),
        ),
        migrations.AddField(
            model_name='customer',
            name='comments',
            field=Core.fields.ForeignKeys.CommentForeignKey.CommentForeignKey(blank=True, help_text='Comment of this Customer record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='Products.comment', verbose_name='Customer`s Comment'),
        ),
        migrations.AddField(
            model_name='customer',
            name='coupon',
            field=Core.fields.ManyToManys.CouponManyToMany.CouponManyToMany(blank=True, db_index=True, help_text='Coupon of this Customer record', related_name='customers', through='Customers.CustomerCoupon', to='Customers.coupon', verbose_name='Customer`s Coupon'),
        ),
        migrations.AddField(
            model_name='customer',
            name='favorite',
            field=Core.fields.ForeignKeys.FavoriteForeignKey.FavoriteForeignKey(blank=True, help_text='Favorite of this Customer record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='Customers.favorite', verbose_name='Customer`s Favorite'),
        ),
        migrations.AddField(
            model_name='customer',
            name='order_customer',
            field=Core.fields.ForeignKeys.OrderCustomerForeignKey.OrderCustomerForeignKey(blank=True, help_text='OrderCustomer of this Customer record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='Customers.ordercustomer', verbose_name='Customer`s OrderCustomer'),
        ),
    ]
