# Generated by Django 4.1.4 on 2023-01-20 17:06

import Core.fields.ForeignKeys.CartForeignKey
import Core.fields.ForeignKeys.CartItemForeignKey
import Core.fields.ForeignKeys.CustomerForeignKey
import Core.fields.ForeignKeys.UserForeignKey
import Core.fields.ForeignKeys.WishListForeignKey
import Core.fields.ManyToManys.CustomerManyToMany
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Customers', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user',
            field=Core.fields.ForeignKeys.UserForeignKey.UserForeignKey(blank=True, help_text='User of this Customer record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to=settings.AUTH_USER_MODEL, verbose_name='Customer`s User'),
        ),
        migrations.AddField(
            model_name='customer',
            name='wish_list',
            field=Core.fields.ForeignKeys.WishListForeignKey.WishListForeignKey(blank=True, help_text='WishList of this Customer record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='Customers.wishlist', verbose_name='Customer`s WishList'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='customer',
            field=Core.fields.ManyToManys.CustomerManyToMany.CustomerManyToMany(blank=True, db_index=True, help_text='Customer of this Coupon record', related_name='coupons', through='Customers.CustomerCoupon', to='Customers.customer', verbose_name='Coupon`s Customer'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=Core.fields.ForeignKeys.CartForeignKey.CartForeignKey(blank=True, help_text='Cart of this Item record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartitems', to='Customers.cart', verbose_name='Item`s Cart'),
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_item',
            field=Core.fields.ForeignKeys.CartItemForeignKey.CartItemForeignKey(blank=True, help_text='CartItem of this Cart record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='Customers.cartitem', verbose_name='Cart`s CartItem'),
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=Core.fields.ForeignKeys.CustomerForeignKey.CustomerForeignKey(blank=True, help_text='Customer of this Cart record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='Customers.customer', verbose_name='Cart`s Customer'),
        ),
    ]
