# Generated by Django 4.1.4 on 2023-01-20 17:26

import Core.fields.ForeignKeys.CouponForeignKey
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercustomer',
            name='CouponCustomerCoupon',
        ),
        migrations.AddField(
            model_name='ordercustomer',
            name='coupon',
            field=Core.fields.ForeignKeys.CouponForeignKey.CouponForeignKey(blank=True, help_text='Order of this Customer record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordercustomers', to='Customers.coupon', verbose_name='Customer`s Order'),
        ),
    ]
