# Generated by Django 4.1.4 on 2023-01-21 08:53

import Core.fields.OneToOnes.CustomerOneToOne
import Core.fields.OneToOnes.MarketOneToOne
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Markets', '0003_alter_inventory_market_alter_market_user'),
        ('Customers', '0006_cartitem_inventory_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=Core.fields.OneToOnes.CustomerOneToOne.CustomerOneToOne(help_text='Customer of this Cart record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='Customers.customer', verbose_name='Cart`s Customer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=Core.fields.OneToOnes.MarketOneToOne.MarketOneToOne(help_text='Market of this Customer record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='Markets.market', verbose_name='Customer`s Market'),
        ),
        migrations.AlterField(
            model_name='customercoupon',
            name='customer_id',
            field=Core.fields.OneToOnes.CustomerOneToOne.CustomerOneToOne(help_text='Customer of this Coupon record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customercoupons', to='Customers.customer', verbose_name='Coupon`s Customer'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='customer',
            field=Core.fields.OneToOnes.CustomerOneToOne.CustomerOneToOne(help_text='Customer of this Favorite record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorites', to='Customers.customer', verbose_name='Favorite`s Customer'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='customer',
            field=Core.fields.OneToOnes.CustomerOneToOne.CustomerOneToOne(help_text='Customer of this Wishlist record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wishlists', to='Customers.customer', verbose_name='Wishlist`s Customer'),
        ),
    ]
