class REQUIREDFIELDS:
    MARKET = []
    INVENTORY = []
    INVENTORYITEM = []
    INVENTORYITEMPROPERTY = []
    PROPERTY = []
    ORDERMARKET = []
class SEARCHFIELDS:
    MARKET = []
    INVENTORY = []
    INVENTORYITEM = []
    INVENTORYITEMPROPERTY = []
    PROPERTY = []
    ORDERMARKET = []
