class REQUIREDFIELDS:
    CUSTOMER = []
    CART = []
    CARTITEM = []
    COUPON= []
    CUSTOMERCOUPON = []
    FAVORITE = []
    FAVORITEITEM = []
    ORDERCUSTOMER = []
    WISHLIST = []
    WISHLISTITEM = []
class SEARCHFIELDS:
    CUSTOMER = []
    CART = []
    CARTITEM = []
    COUPON= []
    CUSTOMERCOUPON = []
    FAVORITE = []
    FAVORITEITEM = []
    ORDERCUSTOMER = []
    WISHLIST = []
    WISHLISTITEM = []
