# Generated by Django 4.1.4 on 2023-01-20 17:55

import Core.fields.ForeignKeys.CustomerForeignKey
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0006_cartitem_inventory_item'),
        ('Products', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=Core.fields.ForeignKeys.CustomerForeignKey.CustomerForeignKey(blank=True, help_text='Author id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments_author', to='Customers.customer', verbose_name='Author'),
        ),
    ]
